services:
  postgres:
    image: postgres:16
    container_name: quickstart_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quickstart_db
      POSTGRES_USER: quickstart_user
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: "redis:alpine"
  #   container_name: quickstart_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  backend:
    build: .
    container_name: quickstart_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
